# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  contentDir: content/en
  title: Alexey Kuzmenkov
  params:
    locale: en-us
    hugoblox:
      identity:
        name: Alexey Kuzmenkov

# Uncomment the lines below to configure your website in a second language.
ru:
  contentDir: content/ru
  title: Алексей Юрьевич Кузьменков
  params:
    locale: ru-ru
    hugoblox:
      identity:
        name: Алексей Юрьевич Кузьменков
