# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  contentDir: content/en
  title: Alexey Kuzmenkov

# Uncomment the lines below to configure your website in a second language.
ru:
  locale: ru
  contentDir: content/ru
  title: Алексей Кузьменков
  params:
    description: Site description in Russian
